In [2]:
import numpy as np
## 創建一維數組
A = np.arange(2, 18)
print(A)
## 索引第七個元素
print(A[6])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
8


In [5]:
## 創建二維數組
A = np.arange(2, 18).reshape((4,4))
print(A)
## 索引第四行
print(A[3])

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[14 15 16 17]


In [7]:
## 索引第二行第三列
print(A[1][2])

8


In [8]:
## 索引第二行第三列
print(A[1, 2])

8


In [10]:
## 索引第二行的第二列到第三列
print(A[1, 1:3])

[7 8]


In [11]:
## 一行一行列印出來
for row in A:
    print(row)

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]
[14 15 16 17]


In [13]:
## 一列一列印出來
for column in np.transpose(A):
    print(column)

[ 2  6 10 14]
[ 3  7 11 15]
[ 4  8 12 16]
[ 5  9 13 17]


In [21]:
import numpy as np

A = np.arange(2,18).reshape((4,4))
print(A)

print('Flatten: ', A.flatten())
print('Flatten: ', A.flat)

for item in A.flat:
    print(item)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
Flatten:  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
Flatten:  <numpy.flatiter object at 0x0000028C54D32730>
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [22]:
import numpy as np
## 創建數組
A = np.array([1,2,3])
B = np.array([4,5,6])

## 垂直合併
C = np.vstack((A,B))
print(C)

[[1 2 3]
 [4 5 6]]


In [25]:
## 列印出合併後的形狀
print(A.shape, B.shape, C.shape)

(3,) (3,) (2, 3)


In [26]:
## 水平合併
D = np.hstack((A,B))
print(D)
print(A.shape, D.shape)

[1 2 3 4 5 6]
(3,) (6,)


In [31]:
print(A)
print(A.shape)

## 水平轉置
print(A[np.newaxis, :])
print(A[np.newaxis, :].shape)

## 垂直轉置
print(A[:, np.newaxis])
print(A[:, np.newaxis].shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]
(3, 1)


In [38]:
import numpy as np
## 創建數組，並轉成垂直
A = np.array([1,2,3])[:, np.newaxis]
B = np.array([4,5,6])[:, np.newaxis]

## 垂直合併
C = np.vstack((A,B))
## 水平合併
D = np.hstack((A,B))

print('A:')
print(A)
print('B:')
print(B)
print('C:')
print(C)
print('D:')
print(D)

print(A.shape, B.shape, C.shape, D.shape)

A:
[[1]
 [2]
 [3]]
B:
[[4]
 [5]
 [6]]
C:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
D:
[[1 4]
 [2 5]
 [3 6]]
(3, 1) (3, 1) (6, 1) (3, 2)


In [47]:
## 多個數組合併

## 垂直合併
E = np.concatenate((A, B, A, B), axis = 0)
print(E)

## 水平合併
F = np.concatenate((A, B, A, B), axis = 1)
print(F)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 4 1 4]
 [2 5 2 5]
 [3 6 3 6]]
