In [2]:
## 導入NumPy套件
import numpy as np

In [5]:
## 將列表轉化為矩陣
array = np.array([[2,4,6],
                  [3,7,9],
                  [1,3,8]])
array

array([[2, 4, 6],
       [3, 7, 9],
       [1, 3, 8]])

In [7]:
## 數組維度
print('number of dim: ', array.ndim)

## 數組的形狀 - 行數核列數
print('array shape: ', array.shape)

## 數組的大小 - 元素個數
print('size: ', array.size)

number of dim:  2
array shape:  (3, 3)
size:  9


In [8]:
## 創建一個數組
a = np.array([2,6,8])
print(a)

[2 6 8]


In [11]:
## 指定創建數組的數據類型
a = np.array([2,6,8], dtype = np.int)
print(a.dtype)

a = np.array([2,6,8], dtype = np.int64)
print(a.dtype)

int32
int64


In [13]:
## 指定創建數組的數據類型
a = np.array([2,6,8], dtype = np.float)
print(a.dtype)

a = np.array([2,6,8], dtype = np.float32)
print(a.dtype)

float64
float32


In [15]:
## 創建數組
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
## 創建值全為0的5行6列數組
a = np.zeros((5,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [21]:
## 創建值全為1的5行6列數組
a = np.ones((5,6))
print(a)
print(a.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
float64


In [23]:
## 創建值全為1的5行6列數組，指定數據類型為int
a = np.ones((5,6), dtype = np.int)
print(a)
print(a.dtype)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
int32


In [34]:
## 創建一個全空，但每個元素值都接近於0的數組
a = np.empty((4,5))
print(a)

## 創建一個全空，但每個元素值都接近於0的數組，並指定數據類型為int
b = np.empty((4,5), dtype = np.int)
print(b)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307
  1.33511018e-306]
 [1.33511969e-306 6.23037996e-307 6.23053954e-307 9.34609790e-307
  8.45593934e-307]
 [9.34600963e-307 3.56036603e-307 1.37961641e-306 1.37961302e-306
  1.11259940e-306]
 [1.60219035e-306 1.11261570e-306 1.06811354e-306 8.34448533e-308
  1.21347091e+295]]
[[ -13901544        605         45          0          0]
 [         0          0          0          0 1819042080]
 [1634607739  975332717 1685353250  578057583 1702109740]
 [ 975336568 1869375010  875983969 1818652252  863265135]]


In [36]:
## 創建一個指定範圍的數組: 0~60，中間隔5的值
a = np.arange(0,60,5)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [40]:
## 創建線段行數據 - 1~20之間切10個點
a = np.linspace(1,20,10)
print(a)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [41]:
## 改變數組形狀
a = np.linspace(1,20,10).reshape((5,2))
print(a)

[[ 1.          3.11111111]
 [ 5.22222222  7.33333333]
 [ 9.44444444 11.55555556]
 [13.66666667 15.77777778]
 [17.88888889 20.        ]]
