In [9]:
import numpy as np

## 創建數組
A = np.arange(20).reshape((5,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [10]:
## 縱向分割 - 切割成兩段
print(np.split(A, 2, axis = 1))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])]


In [11]:
## 橫向切割 - 切成五段
print(np.split(A, 5, axis = 0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]])]


In [12]:
## 當遇到不等量的切割時會報錯
print(np.split(A, 2, axis = 0))
## 因為5沒辦法等量切割成兩段

ValueError: array split does not result in an equal division

In [14]:
print(A)

## 不等量的切割
print(np.array_split(A, 2, axis = 1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])]


In [19]:
print(A)

## 水平切割 等同於np.split(A, 5, axis = 0)
print(np.hsplit(A, 2))

## 垂直切割 等同於np.split(A, 2, axis = 1)
print(np.vsplit(A, 5))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]])]


In [21]:
import numpy as np

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [23]:
## 賦值
b = a
c = a
d = b
print(a, b, c, d)

[0 1 2 3 4 5] [0 1 2 3 4 5] [0 1 2 3 4 5] [0 1 2 3 4 5]


In [27]:
## 當改變a的時候，b、c、d都會跟著改變
a[0] = 11
print(a, b, c, d)

## 判斷b、c、d是否與a一樣
print(b is a)
print(c == a)
print(d is a)

[11  1  2  3  4  5] [11  1  2  3  4  5] [11  1  2  3  4  5] [11  1  2  3  4  5]
True
[ True  True  True  True  True  True]
True


In [28]:
## 更改d值，a、b、c也會更著改變
d[2:5] = [6,6,6]
print(a, b, c, d)

[11  1  6  6  6  5] [11  1  6  6  6  5] [11  1  6  6  6  5] [11  1  6  6  6  5]


In [31]:
## 使用copy創建a的複本e，改變a的時候就不會影響b
e = a.copy()
print(e)
a[1] = 100
print(a)
print(e)
print(a is e)

[ 11 100   6   6   6   5]
[ 11 100   6   6   6   5]
[ 11 100   6   6   6   5]
False
